version: '3'
services:
  app:
    build: docker/elixir/.
    ports:
      - 80
    volumes:
      - .:/app
    links:
      - db
    environment:
      VIRTUAL_HOST: "bobsbest.dev"
    working_dir: /app
    network_mode: "bridge"
    entrypoint: ./docker/elixir/app-entrypoint.sh
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bobsbest
      POSTGRES_PASSWORD: bobsbest
      POSTGRES_DB: bestpest_db
    network_mode: "bridge"
